spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: fastview
    password:

logging:
  config: classpath:logs/logback.xml